name: CD - Build and Release GUI App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: windows-latest

    env:
      NEW_TAG: v1.0.${{ github.run_number }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore TUBES_KPL_KELOMPOK-05.sln

    - name: Build Project
      run: dotnet build TUBES_KPL_KELOMPOK-05.sln --configuration Release

    - name: Publish Application
      run: dotnet publish GUI_TUBES_KPL_KELOMPOK-5/GUI_TUBES_KPL_KELOMPOK-5.csproj --configuration Release --output publish/

    - name: List published files
      run: dir publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-Publish
        path: publish/

    - name: Create and Push Git Tag
      shell: pwsh
      env:
        NEW_TAG: v1.0.${{ github.run_number }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag $env:NEW_TAG
        git remote set-url origin https://x-access-token:${env:PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}
        git push origin $env:NEW_TAG

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.NEW_TAG }}
        name: Release ${{ env.NEW_TAG }}
        files: publish/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
